FROM scratch AS ctx
COPY packages/image-common /common
COPY images/{{ name }} /image

FROM {{ base_image }}

RUN --mount=type=bind,from=ctx,source=/,target=/ctx \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    /ctx/common/build.sh /ctx/image

RUN bootc container lint